"""Initialize the VoxTutor GitHub wiki with 5 pages."""
import os
import subprocess
import tempfile
import textwrap

PAGES = {
    "Home.md": textwrap.dedent("""\
        # VoxTutor

        [![CI](https://github.com/ranafaraz/VoxTutor/actions/workflows/ci.yml/badge.svg)](https://github.com/ranafaraz/VoxTutor/actions/workflows/ci.yml)
        [![Live demo](https://img.shields.io/badge/live%20demo-voxtutor.dexdevs.com-brightgreen?logo=rocket)](https://voxtutor.dexdevs.com)
        [![License: MIT](https://img.shields.io/badge/License-MIT-green.svg)](https://github.com/ranafaraz/VoxTutor/blob/main/LICENSE)

        **A pronunciation-assessment benchmark for spoken-language tutoring.**

        VoxTutor synthesizes learner utterances from a known phoneme inventory with mispronunciations
        injected at *known positions*, then scores four scorers on whether they recover them. The result
        is a clean 2x2 dissociation: **forced alignment (DTW) and Goodness-of-Pronunciation (GOP)
        normalization each buy robustness to a different real-world distortion, and you need both** to
        be robust everywhere.

        - Speaking-rate variation breaks naive fixed-window segmentation; DTW forced alignment fixes it.
        - Channel noise inflates raw frame-to-template distances; GOP normalization fixes it.
        - A scrambled-label null confirms every AUROC signal is real.
        - No acoustic model, no speech corpus, no API keys -- numpy only.

        ## Quick start

        ```bash
        pip install -e ".[dev]"
        voxtutor compare --regime warped
        voxtutor compare --regime noisy
        python -m evals.harness
        pytest -q
        ```

        ## Wiki pages

        - [[Architecture]] -- utterance synthesis, scorer implementations, 2x2 design
        - [[Evaluation]] -- benchmark setup, results table, regime descriptions
        - [[Configuration]] -- env vars, .env.example
        - [[Development]] -- setup, tests, how to add a scorer or regime
    """),

    "Architecture.md": textwrap.dedent("""\
        # Architecture

        ## Overview

        VoxTutor is structured around three concerns: **utterance synthesis** (produce a signal with
        a known answer), **scoring** (measure pronunciation quality), and **evaluation** (recover the
        known answer and assert the dissociation). The scorers are textbook; what is designed is the
        experiment.

        ## Utterance synthesis

        Each utterance is a sequence of N phonemes drawn from a fixed inventory. Each phoneme has a
        canonical template -- a mean feature vector in a small acoustic feature space. Frames are
        generated by sampling around the template with a fixed within-phone variance.

        **Mispronunciation injection.** A random subset of phoneme positions is marked as mispronounced.
        The template is nudged by a confusable amount (large enough to be detectable by a good scorer,
        small enough to cause failures when the ingredient is absent). The ground-truth label vector is
        the binary mask of mispronounced positions.

        **Distortion regimes:**

        | Regime | What changes | Ingredient that fixes it |
        |---|---|---|
        | clean | nothing (control) | -- |
        | warped | speaking rate varied per phoneme (frame count stretched/compressed) | DTW forced alignment |
        | noisy | additive heteroscedastic channel noise (per-utterance noise floor) | GOP normalization |

        ## Scorer implementations

        All scorers are the four corners of a 2x2: **segmentation** x **normalization**.

        **Fixed segmentation (`fixed`).** Splits frames into equal-length chunks, one per phoneme.
        Correct only at constant speaking rate. Under rate variation, phoneme centroids drift.

        **DTW forced alignment (`align`).** Dynamic Time Warping aligns the utterance frame sequence to
        the canonical phoneme sequence. Handles arbitrary per-phoneme rate variation with no tuning.

        **Raw distance (`raw`).** Mean L2 distance from assigned frames to the canonical template.
        Equals the true mispronunciation signal plus within-phone variance. Channel noise inflates it.

        **GOP normalization (`gop-norm`).** Distance of position centroid to template, minus the
        estimated within-phone variance. Removes the channel-level DC offset (Goodness-of-Pronunciation
        likelihood-ratio correction).

        | Scorer | Segmentation | Normalization | Handles rate | Handles noise |
        |---|---|---|---|---|
        | naive | fixed | raw | no | no |
        | aligned | DTW | raw | yes | no |
        | normalized | fixed | gop-norm | no | yes |
        | gop | DTW | gop-norm | yes | yes |

        ## 2x2 dissociation design

        - `naive` (neither): fails on both `warped` and `noisy`.
        - `aligned` (segmentation only): passes `warped`, fails on `noisy`.
        - `normalized` (normalization only): fails on `warped`, passes `noisy`.
        - `gop` (both): passes all regimes.

        ## Module layout

        ```
        voxtutor/
          synthesis/     -- utterance and phoneme generation
          scorers/       -- naive, aligned, normalized, gop implementations
          regimes/       -- clean, warped, noisy distortion generators
          eval/          -- AUROC, dissociation gate, harness
        evals/
          harness.py     -- writes evals/RESULTS.md
          gate.py        -- asserts the 2x2 (CI gate)
        tests/           -- 56 pytest tests
        ```
    """),

    "Evaluation.md": textwrap.dedent("""\
        # Evaluation

        ## Benchmark setup

        - **Utterances:** 40 per cell (scorer x regime), 12 random seeds; results are mean AUROC.
        - **Ground truth:** binary mispronunciation label per phoneme position, injected at synthesis time.
        - **Metric:** AUROC. 1.0 = perfect recovery, 0.5 = chance.
        - **Null:** scrambled ground truth -- every scorer must fall to ~0.50.

        ## Regimes

        | Regime | Description |
        |---|---|
        | clean | Control -- no distortion |
        | warped | Per-phoneme frame count stretched or compressed by a random factor |
        | noisy | Additive heteroscedastic Gaussian noise; per-utterance noise floor |

        ## Results

        Mean AUROC over 12 seeds, 40 utterances/cell.

        | scorer | ingredients | clean | warped | noisy |
        |---|---|--:|--:|--:|
        | random | baseline | 0.491 | 0.509 | 0.508 |
        | naive | fixed + raw | 1.000 | 0.620 | 0.730 |
        | aligned | align + raw | 1.000 | 1.000 | 0.728 |
        | normalized | fixed + gop-norm | 1.000 | 0.662 | 0.999 |
        | **gop** | **align + gop-norm** | **1.000** | **1.000** | **0.999** |

        ## Key findings

        **Effect 1 -- forced alignment beats speaking-rate variation.**
        Fixed-segmentation scorers drop on `warped` (naive 1.000->0.620). DTW scorers stay at 1.000.

        **Effect 2 -- GOP normalization beats channel noise.**
        Raw scorers drop on `noisy` (naive 1.000->0.730, aligned 1.000->0.728). GOP scorers stay at ~1.0.

        Only `gop` (both ingredients) is robust everywhere.

        ## Reproducing the results

        ```bash
        python -m evals.harness   # full table (writes evals/RESULTS.md)
        python -m evals.gate      # CI dissociation gate
        voxtutor compare --regime warped
        voxtutor compare --regime noisy
        voxtutor score --method gop --regime noisy
        ```
    """),

    "Configuration.md": textwrap.dedent("""\
        # Configuration

        All configuration via environment variables. Defaults reproduce the published benchmark.

        ## Environment variables

        | Variable | Default | Description |
        |---|---|---|
        | `VOXTUTOR_METHOD` | `gop` | Scorer: `naive`, `aligned`, `normalized`, `gop`, `random` |
        | `VOXTUTOR_REGIME` | `clean` | Regime: `clean`, `warped`, `noisy` |
        | `VOXTUTOR_LABELS` | *(built-in)* | Path to custom phoneme label file (optional) |
        | `VOXTUTOR_SAMPLES` | `40` | Number of utterances per cell |
        | `VOXTUTOR_SEED` | `42` | Base random seed |
        | `VOXTUTOR_BACKEND` | `numpy` | Compute backend (numpy = offline) |

        ## .env.example

        ```dotenv
        VOXTUTOR_METHOD=gop
        VOXTUTOR_REGIME=clean
        VOXTUTOR_SAMPLES=40
        VOXTUTOR_SEED=42
        VOXTUTOR_BACKEND=numpy
        ```

        ## Usage

        ```bash
        # Run one scorer on one regime
        voxtutor score --method aligned --regime warped

        # Compare all scorers on one regime
        voxtutor compare --regime noisy

        # List regimes and descriptions
        voxtutor regimes
        ```

        ## Reproducibility

        Fix `VOXTUTOR_SEED` and `VOXTUTOR_SAMPLES` to reproduce exact numbers. The published table
        uses `SEED=42`, `SAMPLES=40`, iterated over 12 seeds (42 through 53). The harness handles
        this automatically.
    """),

    "Development.md": textwrap.dedent("""\
        # Development

        ## Setup

        ```bash
        git clone https://github.com/ranafaraz/VoxTutor.git
        cd VoxTutor
        python -m venv .venv
        source .venv/bin/activate  # Windows: .venv\\Scripts\\activate
        pip install -e ".[dev]"
        pytest -q   # 56 tests
        ```

        Optional scipy cross-check: `pip install -e ".[scipy]"`

        ## Running the benchmark

        ```bash
        python -m evals.harness   # full table + RESULTS.md
        python -m evals.gate      # dissociation gate (used in CI)
        voxtutor compare --regime warped
        voxtutor score --method gop --regime noisy
        voxtutor regimes
        ```

        ## Repository structure

        ```
        VoxTutor/
          voxtutor/
            synthesis/    -- phoneme inventory, utterance generator, mispronunciation injector
            scorers/      -- naive.py, aligned.py, normalized.py, gop.py, random_scorer.py
            regimes/      -- clean.py, warped.py, noisy.py
            eval/         -- auroc.py, gate.py
            cli.py        -- voxtutor CLI entry point
          evals/          -- harness.py, gate.py
          tests/          -- 56 pytest tests
          docs/           -- ARCHITECTURE.md, DECISIONS.md, demo.gif
        ```

        ## Adding a scorer

        1. Create `voxtutor/scorers/my_scorer.py` with `score(utterance, phonemes) -> np.ndarray`.
        2. Register in `voxtutor/scorers/__init__.py` under a string key.
        3. Add tests in `tests/test_scorers.py`.
        4. Verify with `voxtutor compare --regime clean`.
        5. Add key to `VOXTUTOR_METHOD` accepted values in Configuration.

        ## Adding a regime

        1. Create `voxtutor/regimes/my_regime.py` with `apply(utterance, rng) -> utterance`.
        2. Register in `voxtutor/regimes/__init__.py` and add description.
        3. Tests: regime must not change ground-truth labels.

        ## CI

        Runs `pytest -q` + `python -m evals.gate` on Python 3.10, 3.11, 3.12. No secrets needed.

        ## Code style

        `black` + `ruff`. All random state via `np.random.default_rng(seed)`.
    """),
}

import json
import urllib.request

TOKEN = os.environ["GH_WIKI_TOKEN"]
REPO = os.environ.get("GITHUB_REPOSITORY", "ranafaraz/VoxTutor")


def gh_api(method, path, body=None):
    url = f"https://api.github.com{path}"
    data = json.dumps(body).encode() if body else None
    req = urllib.request.Request(
        url, data=data, method=method,
        headers={
            "Authorization": f"Bearer {TOKEN}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "Content-Type": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(req) as resp:
            return resp.status, json.loads(resp.read())
    except urllib.error.HTTPError as e:
        return e.code, json.loads(e.read())


# Step 1: try to create the Home page via REST API (initializes the wiki repo)
print("Creating Home page via REST API to bootstrap wiki repo...")
status, resp = gh_api("POST", f"/repos/{REPO}/wiki/pages",
                       {"title": "Home", "content": PAGES["Home.md"]})
print(f"  REST API status: {status} -> {resp.get('message', 'ok')}")

if status in (200, 201):
    # Home created via REST; create remaining pages
    for filename, content in PAGES.items():
        if filename == "Home.md":
            continue
        title = filename.removesuffix(".md")
        status2, resp2 = gh_api("POST", f"/repos/{REPO}/wiki/pages",
                                 {"title": title, "content": content})
        print(f"  Created {title}: {status2} -> {resp2.get('message', 'ok')}")
    print("Done via REST API.")
else:
    # REST API failed (wiki not yet supported for this repo plan, etc.)
    # Fall back to git push approach
    print("REST API unavailable, falling back to git push...")
    with tempfile.TemporaryDirectory() as tmpdir:
        wiki_url = f"https://x-access-token:{TOKEN}@github.com/{REPO}.wiki.git"
        wiki_dir = os.path.join(tmpdir, "wiki")

        result = subprocess.run(["git", "clone", wiki_url, wiki_dir],
                                capture_output=True, text=True)
        if result.returncode != 0:
            print("Wiki repo doesn't exist yet, initializing fresh...")
            os.makedirs(wiki_dir)
            subprocess.run(["git", "init"], cwd=wiki_dir, check=True)
            subprocess.run(["git", "remote", "add", "origin", wiki_url],
                           cwd=wiki_dir, check=True)

        for filename, content in PAGES.items():
            path = os.path.join(wiki_dir, filename)
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"Wrote {filename}")

        subprocess.run(["git", "config", "user.name", "Rana Faraz"],
                       cwd=wiki_dir, check=True)
        subprocess.run(["git", "config", "user.email", "faraz.ahmed@iub.edu.pk"],
                       cwd=wiki_dir, check=True)
        subprocess.run(["git", "add", "."], cwd=wiki_dir, check=True)

        result = subprocess.run(
            ["git", "-c", "user.name=Rana Faraz",
             "-c", "user.email=faraz.ahmed@iub.edu.pk",
             "commit", "-m", "docs: initialize project wiki"],
            cwd=wiki_dir, capture_output=True, text=True
        )
        print(result.stdout)
        for branch in ["master", "main"]:
            push = subprocess.run(
                ["git", "push", "-u", "origin", f"HEAD:{branch}"],
                cwd=wiki_dir, capture_output=True, text=True
            )
            if push.returncode == 0:
                print(f"Pushed to {branch} successfully!")
                break
            else:
                print(f"Push to {branch} failed: {push.stderr}")
    print("Done.")
